meilisearch:
    url: '%env(MEILISEARCH_URL)%' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    indices:
        - name: posts
          class: App\Entity\Post
          index_if: 'isPublished'
          enable_serializer_groups: true
          serializer_groups: ['searchable']
